package com.webmd.api;

public enum Diseases {
ALCOHOLIC, ALLERGIES, AMPUTATION, ANXIETY, ARTHRITIS, ASPERGERS, ASTHMA, ADHD, AUTISM, AUTISM_SPECTRUM, BIPOLAR, BLEEDING, BILNDNESS, BRAIN_INJURY, BURN_INJURY, CANCER, CELIAC, CEREBRAL_PALSY, CHRONIC_FATIGUE, CHRONIC_ILLNESS, CLEFT_LIP, CLEFT_PALATE, CROHNS, CYSTIC_FIBROSIS, DEAF, HARD_HEARING, DEPRESSION, DIABETES, DOWN_SYNDROM, DRUG_ADDICTION, DWARFISM, EATING_DISORDER, ENDOMETRIOSIS, EPILEPSY, ECZEMA, FETAL_ALCOHOL, FIBROMYALGIA, GERD, GROWTH_HORMONE_DEFICIENT, HEART_DISEASES, HIV, AIDS, HUNTINGTONS, IBD, INTELLECTUAL, JV_RHEUMATOID_ARTHRITIS, KIDNEY_DISEASE, LACTOSE_INTOLERANT
}
