package com.webmd.api;

public enum Medications {
ADVIL, ALEVE, CEPACOL, DIMETAPP, CLARITIN, COLACE, CORTAID, DUCOLAX, EXCEDRIN, GAVISCON, LOTRIMIN, ANATACID, MIDOL, MOTRIN, ORAJEL, PEPTO_BISMOL, ROLAIDS, TAGAMET, TYLENOL, ZANTAC, ZYRTEC
}
