package com.webmd.api;

public enum Symptoms {
CHEST_PAIN, HEADACHE, FATIGUE, ABDOMINAL_PAIN, NO_APPETITE, EAR_PAIN, SWEATING, SORE,
HAIR_LOSS, DRY_SKIN, BLEEDING, WOUNDED, VISION_LOSS, FACIAL_PAIN, ORAL_PAIN
}
